---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

title: FOSS@RIT Profiles
repository: FOSSRIT/people
author: RIT
email: foss@rit.edu
description: Interactive directory of FOSS@RIT community members
github_username: FOSSRIT


# --- general settings ---

baseurl: /people
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links


# --- theme settings ---

theme: minima
header_pages:
  - faculty.html
  - student.html
  - mentor.html
  - alum.html


# --- build settings ---

# https://jekyllrb.com/docs/continuous-integration/travis-ci/
exclude:
  - _ignore
  - example_profile.yaml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Rakefile
  - README.md
  - vendor
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty  # no .html extensions
